# Generated by Django 4.1.1 on 2022-10-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_about', models.TextField(default=None, max_length=800)),
                ('user_age', models.IntegerField(null=True)),
                ('user_city', models.TextField(max_length=255)),
                ('user_country', models.TextField(max_length=255)),
                ('user_email', models.TextField(max_length=255, unique=True)),
                ('user_first_name', models.TextField(max_length=255)),
                ('user_jop_title', models.TextField(max_length=255)),
                ('user_last_name', models.TextField(max_length=255)),
                ('user_password', models.TextField(max_length=255)),
                ('user_phone', models.TextField(max_length=13, unique=True)),
            ],
        ),
    ]
