# Generated by Django 4.1.1 on 2022-10-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.TextField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('experience_place', models.TextField(max_length=255)),
                ('experience_position', models.TextField(max_length=255)),
                ('start_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('education_degree', models.TextField(max_length=255)),
                ('education_place', models.TextField(max_length=255)),
                ('end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.TextField(max_length=255)),
                ('course_provider', models.TextField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
