# Generated by Django 4.1.1 on 2022-10-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_skill_experience_education_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.TextField(max_length=100),
        ),
    ]
